# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    setup:
        docker:
            - image: circleci/node:14.15.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    test:
        docker:
            - image: circleci/node:14.15.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - run:
                name: Build
                command: NODE_ENV=production yarn build
            - run:
                name: Test
                command: NODE_ENV=production yarn test
    build:
        docker:
            - image: circleci/node:14.15.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - run:
                name: Build
                command: NODE_ENV=production yarn build
    lint:
        docker:
            - image: circleci/node:14.15.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: NODE_ENV=development yarn
            - run:
                name: Build
                command: NODE_ENV=production yarn build
            - run:
                name: Lint
                command: NODE_ENV=development yarn lint
    clean-lock:
        docker:
            - image: circleci/node:14.15.1
        steps:
            - checkout
            - run:
                name: Clean yarn.lock
                command: NODE_ENV=development node ./scripts/cleanLock.js
workflows:
    version: 2
    build_and_lint:
        jobs:
            - setup
            - clean-lock
            - build:
                requires:
                    - setup
            - test:
                requires:
                    - setup
                    - build
            # This is disabled because it takes up too much memory on the CI container to run and we have husky precommit
            # - lint:
            #     requires:
            #         - setup
            #         - build
